spring:
  application:
    name: sales-service-rest-h2
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:sales}
    username: ${DB_USER:sales}
    password: ${DB_PASSWORD:sales}
  flyway:
    locations: classpath:db/migration

server:
  port: ${SERVER_PORT:8082}
  http2:
    enabled: true
  ssl:
    enabled: ${SSL_ENABLED:false}
    key-store: ${SSL_KEYSTORE:file:/certs/sales-service-rest-h2/keystore.p12}
    key-store-password: ${SSL_KEYSTORE_PASSWORD:changeit}
    key-store-type: PKCS12
